application: funrdf
version: 1
runtime: python
api_version: 1

handlers:
- url: /_ah/xmpp/message/chat/
  script: chatty.py
- url: .*
  script: main.py


inbound_services:
- xmpp_message

