application: funrdf
version: 1
runtime: python
api_version: 1

handlers:
- url: /_ah/xmpp/message/chat/
  script: chatty.py
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
- url: /static/svg
  static_dir: static/svg
  mime_type: image/svg+xml
- url: .*
  script: main.py


inbound_services:
- xmpp_message

