
# pma EmailSignupModel
# 30 states, 100 transitions, 6 accepting states, 0 finished and 0 deadend states

# actions here are just labels, but must be symbols with __name__ attribute

def Initialize(): pass
def ReadInt(): pass
def Login(): pass
def Logout(): pass
def UpdateInt(): pass

# states, key of each state here is its number in graph etc. below

states = {
  0 : {'EmailSignupModel': {'userToInt': {}, 'mode': 'Initializing', 'usersLoggedIn': []}},
  1 : {'EmailSignupModel': {'userToInt': {}, 'mode': 'Running', 'usersLoggedIn': []}},
  2 : {'EmailSignupModel': {'userToInt': {}, 'mode': 'Running', 'usersLoggedIn': ['OleBrumm']}},
  3 : {'EmailSignupModel': {'userToInt': {}, 'mode': 'Running', 'usersLoggedIn': ['VinniPuhh']}},
  4 : {'EmailSignupModel': {'userToInt': {}, 'mode': 'Running', 'usersLoggedIn': ['OleBrumm', 'VinniPuhh']}},
  5 : {'EmailSignupModel': {'userToInt': {'OleBrumm': 2}, 'mode': 'Running', 'usersLoggedIn': ['OleBrumm']}},
  6 : {'EmailSignupModel': {'userToInt': {'OleBrumm': 1}, 'mode': 'Running', 'usersLoggedIn': ['OleBrumm']}},
  7 : {'EmailSignupModel': {'userToInt': {}, 'mode': 'Running', 'usersLoggedIn': ['VinniPuhh', 'OleBrumm']}},
  8 : {'EmailSignupModel': {'userToInt': {'VinniPuhh': 1}, 'mode': 'Running', 'usersLoggedIn': ['VinniPuhh']}},
  9 : {'EmailSignupModel': {'userToInt': {'VinniPuhh': 2}, 'mode': 'Running', 'usersLoggedIn': ['VinniPuhh']}},
  10 : {'EmailSignupModel': {'userToInt': {'VinniPuhh': 1}, 'mode': 'Running', 'usersLoggedIn': ['OleBrumm', 'VinniPuhh']}},
  11 : {'EmailSignupModel': {'userToInt': {'OleBrumm': 2}, 'mode': 'Running', 'usersLoggedIn': ['OleBrumm', 'VinniPuhh']}},
  12 : {'EmailSignupModel': {'userToInt': {'OleBrumm': 1}, 'mode': 'Running', 'usersLoggedIn': ['OleBrumm', 'VinniPuhh']}},
  13 : {'EmailSignupModel': {'userToInt': {'VinniPuhh': 2}, 'mode': 'Running', 'usersLoggedIn': ['OleBrumm', 'VinniPuhh']}},
  14 : {'EmailSignupModel': {'userToInt': {'OleBrumm': 2}, 'mode': 'Running', 'usersLoggedIn': []}},
  15 : {'EmailSignupModel': {'userToInt': {'OleBrumm': 1}, 'mode': 'Running', 'usersLoggedIn': []}},
  16 : {'EmailSignupModel': {'userToInt': {'VinniPuhh': 1}, 'mode': 'Running', 'usersLoggedIn': ['VinniPuhh', 'OleBrumm']}},
  17 : {'EmailSignupModel': {'userToInt': {'OleBrumm': 2}, 'mode': 'Running', 'usersLoggedIn': ['VinniPuhh', 'OleBrumm']}},
  18 : {'EmailSignupModel': {'userToInt': {'OleBrumm': 1}, 'mode': 'Running', 'usersLoggedIn': ['VinniPuhh', 'OleBrumm']}},
  19 : {'EmailSignupModel': {'userToInt': {'VinniPuhh': 2}, 'mode': 'Running', 'usersLoggedIn': ['VinniPuhh', 'OleBrumm']}},
  20 : {'EmailSignupModel': {'userToInt': {'VinniPuhh': 1}, 'mode': 'Running', 'usersLoggedIn': []}},
  21 : {'EmailSignupModel': {'userToInt': {'VinniPuhh': 2}, 'mode': 'Running', 'usersLoggedIn': []}},
  22 : {'EmailSignupModel': {'userToInt': {'OleBrumm': 2, 'VinniPuhh': 1}, 'mode': 'Running', 'usersLoggedIn': ['OleBrumm', 'VinniPuhh']}},
  23 : {'EmailSignupModel': {'userToInt': {'VinniPuhh': 1}, 'mode': 'Running', 'usersLoggedIn': ['OleBrumm']}},
  24 : {'EmailSignupModel': {'userToInt': {'OleBrumm': 1, 'VinniPuhh': 1}, 'mode': 'Running', 'usersLoggedIn': ['OleBrumm', 'VinniPuhh']}},
  25 : {'EmailSignupModel': {'userToInt': {'OleBrumm': 2}, 'mode': 'Running', 'usersLoggedIn': ['VinniPuhh']}},
  26 : {'EmailSignupModel': {'userToInt': {'OleBrumm': 2, 'VinniPuhh': 2}, 'mode': 'Running', 'usersLoggedIn': ['OleBrumm', 'VinniPuhh']}},
  27 : {'EmailSignupModel': {'userToInt': {'OleBrumm': 1}, 'mode': 'Running', 'usersLoggedIn': ['VinniPuhh']}},
  28 : {'EmailSignupModel': {'userToInt': {'OleBrumm': 1, 'VinniPuhh': 2}, 'mode': 'Running', 'usersLoggedIn': ['OleBrumm', 'VinniPuhh']}},
  29 : {'EmailSignupModel': {'userToInt': {'VinniPuhh': 2}, 'mode': 'Running', 'usersLoggedIn': ['OleBrumm']}},
}

# initial state, accepting states, frontier states, deadend states

initial = 0
accepting = [0, 1, 14, 15, 20, 21]
frontier = [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]
finished = []
deadend = []
runstarts = [0]

# finite state machine, list of tuples: (current, (action, args, result), next)

graph = (
  (0, (Initialize, (), None), 1),
  (1, (Login, ('OleBrumm', 'Incorrect'), 'Failure'), 1),
  (1, (Login, ('VinniPuhh', 'Incorrect'), 'Failure'), 1),
  (1, (Login, ('OleBrumm', 'Correct'), 'Success'), 2),
  (1, (Login, ('VinniPuhh', 'Correct'), 'Success'), 3),
  (2, (Login, ('VinniPuhh', 'Incorrect'), 'Failure'), 2),
  (2, (Login, ('VinniPuhh', 'Correct'), 'Success'), 4),
  (2, (Logout, ('OleBrumm',), None), 1),
  (2, (UpdateInt, ('OleBrumm', 2), None), 5),
  (2, (UpdateInt, ('OleBrumm', 1), None), 6),
  (2, (ReadInt, ('OleBrumm',), 0), 2),
  (3, (Login, ('OleBrumm', 'Correct'), 'Success'), 7),
  (3, (ReadInt, ('VinniPuhh',), 0), 3),
  (3, (UpdateInt, ('VinniPuhh', 1), None), 8),
  (3, (Login, ('OleBrumm', 'Incorrect'), 'Failure'), 3),
  (3, (Logout, ('VinniPuhh',), None), 1),
  (3, (UpdateInt, ('VinniPuhh', 2), None), 9),
  (4, (ReadInt, ('VinniPuhh',), 0), 4),
  (4, (UpdateInt, ('VinniPuhh', 1), None), 10),
  (4, (Logout, ('OleBrumm',), None), 3),
  (4, (UpdateInt, ('OleBrumm', 2), None), 11),
  (4, (Logout, ('VinniPuhh',), None), 2),
  (4, (UpdateInt, ('OleBrumm', 1), None), 12),
  (4, (ReadInt, ('OleBrumm',), 0), 4),
  (4, (UpdateInt, ('VinniPuhh', 2), None), 13),
  (5, (Logout, ('OleBrumm',), None), 14),
  (5, (ReadInt, ('OleBrumm',), 2), 5),
  (5, (Login, ('VinniPuhh', 'Incorrect'), 'Failure'), 5),
  (5, (UpdateInt, ('OleBrumm', 2), None), 5),
  (5, (Login, ('VinniPuhh', 'Correct'), 'Success'), 11),
  (5, (UpdateInt, ('OleBrumm', 1), None), 6),
  (6, (UpdateInt, ('OleBrumm', 2), None), 5),
  (6, (Login, ('VinniPuhh', 'Incorrect'), 'Failure'), 6),
  (6, (Login, ('VinniPuhh', 'Correct'), 'Success'), 12),
  (6, (Logout, ('OleBrumm',), None), 15),
  (6, (ReadInt, ('OleBrumm',), 1), 6),
  (6, (UpdateInt, ('OleBrumm', 1), None), 6),
  (7, (ReadInt, ('VinniPuhh',), 0), 7),
  (7, (UpdateInt, ('VinniPuhh', 1), None), 16),
  (7, (Logout, ('OleBrumm',), None), 3),
  (7, (UpdateInt, ('OleBrumm', 2), None), 17),
  (7, (Logout, ('VinniPuhh',), None), 2),
  (7, (UpdateInt, ('OleBrumm', 1), None), 18),
  (7, (ReadInt, ('OleBrumm',), 0), 7),
  (7, (UpdateInt, ('VinniPuhh', 2), None), 19),
  (8, (Login, ('OleBrumm', 'Correct'), 'Success'), 16),
  (8, (UpdateInt, ('VinniPuhh', 1), None), 8),
  (8, (ReadInt, ('VinniPuhh',), 1), 8),
  (8, (Login, ('OleBrumm', 'Incorrect'), 'Failure'), 8),
  (8, (Logout, ('VinniPuhh',), None), 20),
  (8, (UpdateInt, ('VinniPuhh', 2), None), 9),
  (9, (Login, ('OleBrumm', 'Correct'), 'Success'), 19),
  (9, (UpdateInt, ('VinniPuhh', 1), None), 8),
  (9, (Login, ('OleBrumm', 'Incorrect'), 'Failure'), 9),
  (9, (ReadInt, ('VinniPuhh',), 2), 9),
  (9, (Logout, ('VinniPuhh',), None), 21),
  (9, (UpdateInt, ('VinniPuhh', 2), None), 9),
  (10, (UpdateInt, ('VinniPuhh', 1), None), 10),
  (10, (ReadInt, ('VinniPuhh',), 1), 10),
  (10, (Logout, ('OleBrumm',), None), 8),
  (10, (UpdateInt, ('OleBrumm', 2), None), 22),
  (10, (Logout, ('VinniPuhh',), None), 23),
  (10, (UpdateInt, ('OleBrumm', 1), None), 24),
  (10, (ReadInt, ('OleBrumm',), 0), 10),
  (10, (UpdateInt, ('VinniPuhh', 2), None), 13),
  (11, (ReadInt, ('VinniPuhh',), 0), 11),
  (11, (UpdateInt, ('VinniPuhh', 1), None), 22),
  (11, (ReadInt, ('OleBrumm',), 2), 11),
  (11, (Logout, ('OleBrumm',), None), 25),
  (11, (UpdateInt, ('OleBrumm', 2), None), 11),
  (11, (Logout, ('VinniPuhh',), None), 5),
  (11, (UpdateInt, ('OleBrumm', 1), None), 12),
  (11, (UpdateInt, ('VinniPuhh', 2), None), 26),
  (12, (ReadInt, ('VinniPuhh',), 0), 12),
  (12, (UpdateInt, ('OleBrumm', 2), None), 11),
  (12, (UpdateInt, ('VinniPuhh', 1), None), 24),
  (12, (Logout, ('OleBrumm',), None), 27),
  (12, (ReadInt, ('OleBrumm',), 1), 12),
  (12, (Logout, ('VinniPuhh',), None), 6),
  (12, (UpdateInt, ('OleBrumm', 1), None), 12),
  (12, (UpdateInt, ('VinniPuhh', 2), None), 28),
  (13, (UpdateInt, ('OleBrumm', 2), None), 26),
  (13, (UpdateInt, ('VinniPuhh', 1), None), 10),
  (13, (Logout, ('OleBrumm',), None), 9),
  (13, (ReadInt, ('VinniPuhh',), 2), 13),
  (13, (Logout, ('VinniPuhh',), None), 29),
  (13, (UpdateInt, ('OleBrumm', 1), None), 28),
  (13, (ReadInt, ('OleBrumm',), 0), 13),
  (13, (UpdateInt, ('VinniPuhh', 2), None), 13),
  (14, (Login, ('OleBrumm', 'Incorrect'), 'Failure'), 14),
  (14, (Login, ('VinniPuhh', 'Incorrect'), 'Failure'), 14),
  (14, (Login, ('OleBrumm', 'Correct'), 'Success'), 5),
  (14, (Login, ('VinniPuhh', 'Correct'), 'Success'), 25),
  (15, (Login, ('OleBrumm', 'Incorrect'), 'Failure'), 15),
  (15, (Login, ('VinniPuhh', 'Incorrect'), 'Failure'), 15),
  (15, (Login, ('OleBrumm', 'Correct'), 'Success'), 6),
  (15, (Login, ('VinniPuhh', 'Correct'), 'Success'), 27),
  (16, (UpdateInt, ('VinniPuhh', 1), None), 16),
  (16, (ReadInt, ('VinniPuhh',), 1), 16),
  (16, (Logout, ('OleBrumm',), None), 8),
)
